version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: vise-redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-cache:/data
    command: redis-server --appendonly yes --appendfsync everysec
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-cache:
    driver: local
