apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://monitoring-prometheus:9090
    isDefault: true
    editable: true
    
  - name: Loki
    type: loki
    access: proxy
    url: http://monitoring-loki:3100
    editable: true
    
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://monitoring-jaeger:16686
    editable: true